### ISSUE TITLE
what to do if ref and test data have different categories in chisquare?

### ISSUE THREAD

**Issue by AsiehH** [SeldonIO/alibi-detect#191]
I have a question that I think should have been taken into account in this library but I can't find the solution. 

Currently if the reference data has a category feature that is different from that of the test data, we will get an error when we call the predict method in `TabularDrift` or `ChiSquareDrift`. 
I created `categories_per_feature` on the whole data but the way I split the data, one of the features of my reference data has categories from 0 to 11, and  0 to 12 for test data. 
The error I get is 
`operands could not be broadcast together with shapes (13,) (12,) `
This error comes from `chisquare` function under the hood. 

I think this is not a rare incident and it is probable that the reference data does not have all the categories of the test data for one or more features.

**Comment by jklaise** [comment]
This is definitely a use case we want to cover more carefully. One thing to note is that if you know *a priori* how many categories are to be expected per feature then you should put them all in `categories_per_feature`, i.e. in your case you know there are 13 even if the reference set has 12.

More generally, of course, new categories may appear at test time which you did not know about. There are a couple of options we could explore in this case, two that come to mind:
- Explicitly add an extra "unknown" category per feature and provide some way of pre-processing the test data to ensure that all unseen categories are put into the "unknown" bucket
- When new categories are encountered, make sure the reference dataset and the `categories_per_feature` metadata are update to reflect this new reality.

@arnaudvl would be good to hear your thoughts?

**Comment by arnaudvl** [comment]
Hi @AsiehH , for the vanilla Chi^2 test you can't have 0 values for a category in the reference dataset as this leads to divide by 0 issues, the test statistic goes to `inf` and p-value equals 0. The following formula ([from wikipedia](https://en.wikipedia.org/wiki/Chi-squared_test)) applies:

![image](https://user-images.githubusercontent.com/13081602/112618115-b8c44b80-8e1d-11eb-92b0-db5b5e8785d3.png),

where _mi_ refers to the observations of category _i_ in the reference data. We could by default return the `inf` statistic and 0 p-value when new categories are observed with a warning. But beyond that we would want to add methods which deal with this in a more robust way.

**Comment by AsiehH** [comment]
Hi @arnaudvl,

Thanks for the response. 
Yes, in fact what I did was to use the whole dataset to create `categories_per_feature` before splitting. This solves the problem. 
To respond to your suggestion in the first reply, I think a general thing should be taken into account and that is, that sometimes there are categories in the ref that don't exist in the test and vice-versa. So the way unknown would be taken into account is 2-way. But I think if we create `categories_per_feature`  from the whole dataset as I did, this will be resolved. Is there any reason why we shouldn't use this approach?

Also, I have another related question now.
When I look at the the features for which `ChiSquareDrift` did not detect any drift, I see that the p-values of all these features are `NaN` . I do not know what this means and why it happens. I dug a bit more by getting the `value_counts` of these features in the reference and test set. I do not have any missing values. For instance, for one feature, I have the following result:

1. Only one category in both sets, no drift, p_value=`NaN`
2. For another feature I have 
reference data
`cat  count`
`3    568762`
`5     30539`
`1     19228`
`6       374`
test data
`cat  count`
`3    911057`
`1     37269`
`5     27668`
`6      1064`

Thanks, 
Asieh

**Comment by jklaise** [comment]
If you look at the [chi-square test statistic](https://wikimedia.org/api/rest_v1/media/math/render/svg/53b18fe1fe297a80676f41be3b107fe76b4e535b) the denominator `m_i` is the expected number of points with category `i` in the reference data. Because we use a reference dataset to infer `m_i` this means that if the reference dataset does not contain any points with category `i` the test statistic will be undefined even if the test dataset has points with category `i`.

I think there may be a valid use case where, instead of inferring the `m_i` from a reference dataset, we could allow the user to specify the expected proportions `p_i` for each category extrinsic to any reference dataset which would avoid inferring zero prevalence when it is expected to be non-zero @arnaudvl ?

> For features where I have all the categories of the whole dataset in both reference and test set, I have 0 as p-value.

I'm not sure why this happens, I would make sure first of all that all categories for the feature are encoded as `0,...,n_cat-1`. Of course it's possible that the p-value is zero because of extreme drift between the two sets (can confirm visually by plotting the distributions).

**Comment by tjhallum** [comment]
@jklaise / @arnaudvl,

I am experiencing a difficulty with TabularDrift that's very similar to that expressed by @AsiehH.

I created categories_per_feature and a TabularDrift detector using some historical data as the reference set. Then, once I'd accumulated a batch of new data from my data stream, I used that as the test set. However, this resulted in errors that were rooted in the fact that my test set contained new categorical classes that were not present in my original reference set.

Personally, I would benefit greatly from more robust TabularData/ChiSquareDrift functions capable of accommodating the emergence of new & disappearance of old classes in the test set's categorical features (in contrast to my situation, if I understood correctly, it was the disappearance of old classes in the test set that caused problems for @AsiehH).

Additionally, considering that the emergence of new & disappearance of old classes is probably one of the most common manifestations of real-world concept drift, I'd hazard to guess that this functionality would benefit a great many others as well.

Thank you kindly for entertaining this feature enhancement request 🙏!!!

**Comment by arnaudvl** [comment]
Hi @tjhallum , the disappearance of old classes should be handled fine and just result in a 0 count for the missing test set category in `X_count = self._get_counts(X)` [here](https://github.com/SeldonIO/alibi-detect/blob/master/alibi_detect/cd/chisquare.py#L111). It is the emergence of new classes which causes the issue and lead to an error. When designing the ChiSquare detector we assumed you would know in advance which categories could occur (even if they have 0 counts in the reference data) by setting the optional `categories_per_feature` kwarg and otherwise simply infer it from the provided reference data. It seems this might have been too strong of an assumption? One option is to alter this and update the possible reference categories dependent on the test batch. Please note though that even if we accomodate for this it would lead to `inf` test-statistic and 0 p-value, check [this reply](https://github.com/SeldonIO/alibi-detect/issues/191#issuecomment-808107102).
It is worth for us to also look into more sophisticated methods that address this issue in a more robust manner @ojcobb .

**Comment by tjhallum** [comment]
@arnaudvl,

First, thank you for thoughtfully considering my recommendation and responding so promptly!

In response to what you said, yes, think the assumption was too strong.

Of course, I can only speak for my own case, but I certainly do _not_ know in advance all the potential classes that might emerge for my categorical features in future observations - I'm constantly reminded that the world is anything but static 😂!

I mean, as an easily relatable / tangible example, imagine if you were doing drift detection on the given names of babies in a particular English speaking country from year to year. Of course, there would be drift in the trusty mainstays like "Robert", "Elizabeth", "Luke", "Jennifer", "Mark", etc. - which would be present in both the reference and test sets. But...then along comes Elon Musk...and he names his kid "X Æ A-Xii" - a new class in the test set that definitely couldn't have been forecasted until the moment when it happened.

In the real world, novel things happen with surprising frequency, and I think many of Alibi-Detect's users would benefit from TabularDrift/ChiSquareDriftwe functions that are capable of accommodating those novel classes when running drift detection.

For this reason, I think there's merit in your suggestion to investigate more sophisticated methods.

**Comment by arnaudvl** [comment]
> Of course, I can only speak for my own case, but I certainly do not know in advance all the potential classes that might emerge for my categorical features in future observations - I'm constantly reminded that the world is anything but static!

We obviously agree with that but saw it more in the context of drift detection on inputs for machine learning models. A lot of models will simply break if they are presented with categories that were not seen during training. But we also want to facilitate your use case so will try and put a fix in place. My plate is pretty full this week with #198 but will aim to add the fix in next week.

> I mean, as an easily relatable / tangible example, imagine if you were doing drift detection on the given names of babies in a particular English speaking country from year to year. Of course, there would be drift in the trusty mainstays like "Robert", "Elizabeth", "Luke", "Jennifer", "Mark", etc. - which would be present in both the reference and test sets. But...then along comes Elon Musk...and he names his kid "X Æ A-Xii" - a new class in the test set that definitely couldn't have been forecasted until the moment when it happened.

Great example! However our text drift detector would handle this relatively gracefully. :)

**Comment by tjhallum** [comment]
@arnaudvl, next week would be amazing!!!

I'm very grateful for your concern regarding my desired application of TabularDrift and for your willingness to address the need swiftly.

I can promise that I'll productively make use of the enhancement as soon as you implement it!!!

Thank you 🙏!!!

**Comment by AsiehH** [comment]
Thanks @jklaise and arnaudvl for the explanation. 
I actually used `categories_per_feature` on my whole dataset before splitting into ref and test to avoid the error that I received if I defined `categories_per_feature` on my reference data. 
My solution/workaround for the NaN p-value until the new release is to update my reference dataset with 1 count of the categories that only exist in test set. This would solve the problem of NaN p-values. Of course this will not give us a hint about the new categories that emerge and old categories that cease to exist. This is another pre-processing step that I should do prior to training the drift detector.

**Comment by tjhallum** [comment]
> We obviously agree with that but saw it more in the context of drift detection on inputs for machine learning models. A lot of models will simply break if they are presented with categories that were not seen during training. But we also want to facilitate your use case so will try and put a fix in place. My plate is pretty full this week with #198 but will aim to add the fix in next week.

I forgot to speak specifically to this in my previous reply. In line with your vision, I am in fact using `TabularDrift` on inputs for machine learning models. It's just that in my case I've specifically setup my models so that they do not break when encountering new classes not previously seen during training.

**Comment by arnaudvl** [comment]
@tjhallum and @AsiehH : addressed by #222
