### ISSUE TITLE
Add alibi-detect version to metadata

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#236]

**Comment by jklaise** [comment]
Check alibi for an example of setting it, the module also has code for validating and raising a warning if mismatched upon loading: https://github.com/SeldonIO/alibi/blob/90ff57ed7d81bbfcbc8c544fda1472418356f293/alibi/saving.py#L93

**Comment by jklaise** [comment]
To do this properly we would also have to do #216. To clarify, if we fetch the `__version__` string from `alibi.version` at the time of saving the detector (the object doesn't have an associated version attribute), what can happen is the following:
 - Detector gets saved and obtains a `_version: 0.7.2`  entry in the `meta` attribute
 - Detector gets loaded in a new version of the library, we check and raise a warning
 - Detector gets saved again and because of fetching the runtime `__version__` it's version entry is updated `_version: 0.7.3`
This is misleading and can lead to broken artefacts even if the version attributes "match" incorrectly.

The better way to do is is an in `alibi` (see above), where each detector gets a `_version` class attribute upon declaration of the class. Then this is fetched upon saving and added to metadata. When a detector is reloaded in a different version a warning is issued and when it is re-saved, the correct (old) `_version` is fetched from the detector class attribute (the whole class is serialized by `dill` so this is not over-written by the new runtime class definition) and saved, so we avoid overwriting the version in the detector metadata with the incorrect (runtime) version.

**Comment by jklaise** [comment]
Tinkering with `alibi` I noticed that this doesn't actually work as intended and a previously-saved explainer loaded into a new `alibi` version is assigned the new (incorrect) version attribute.

One easy way to fix this is instead of raising a warning just raise an exception and completely disallow trying to use an artefact with a different version of the library.
