### ISSUE TITLE
chi-square test: data size issue

### ISSUE THREAD

**Issue by msank00** [SeldonIO/alibi-detect#287]
Hi Team,

First of all, thanks for providing such a nice package. I have a query regarding the chi-square test. In Alibi detect, the chi-square test is performing fine when the two dataset size is different. If seems there is some sort of normalization. But if I do the same chi-square test using SciPy library, the result will vary if the dataset size is different. Could you please elaborate how this normalization is working? Is there any documentation?

**Comment by arnaudvl** [comment]
Hi @msank00 , thanks for the kind words. The Chi^2 test is done using [scipy.stats.chi2_contingency](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html) as you can see [here](https://github.com/SeldonIO/alibi-detect/blob/master/alibi_detect/cd/chisquare.py#L118). The test is done on the frequencies (counts) in a contingency table and is not normalized. Instead of a goodness-of-fit test of the observed data against the empirical distribution of the reference data, we perform a test for homogeneity which can be interpreted as identifying the distribution most likely to have generated both the reference and test data and perform a goodness-of-fit test on that. The difference will be mainly seen on smaller datasets where the goodness-of-fit test biases towards extreme p-values. For more info check this [older PR](https://github.com/SeldonIO/alibi-detect/pull/203).
