### ISSUE TITLE
No such file or directory meta.dill

### ISSUE THREAD

**Issue by matteoguarrera** [SeldonIO/alibi-detect#318]
When testing the _**VAE outlier detection on CIFAR10**_ notebook I got this error downloading the pretrained model remotelly. No such file or directory meta.dill
Am I doing something wrong?

**Comment by ascillitoe** [comment]
Hi @matteoguarrera, thanks for flagging this. It does look like it might be a minor bug with the `fetch_detector` method. We will address this ASAP but if you want to keep going with the notebook in the meantime, you could either manually create the `my_path/OutlierVAE` directory first, or set `load_outlier_detector = False` to train a new detector from scratch.

**Comment by matteoguarrera** [comment]
The fastest way to overcome this issue is to fetch a previous commit. 
`pip install git+git://github.com/SeldonIO/alibi-detect.git@e58a3af0e5f983fdbcdd4259c3fd843732c0084f
`

**Comment by ascillitoe** [comment]
Ah ha good spot. Seems like there are actually a few different issues here:

1. Use of `os.mkdir()` in `fetch_detector` can't create the nested directory i.e. relies on `my_path` already being created.
2. I am having trouble with `tf.keras.utils.get_file()` (used in `fetch_enc_dec`) when trying to set `fname` to an absolute path. i.e. 
`tf.keras.utils.get_file(fname='my_path/OutlierVAE/model/encoder_net.h5',
                  origin='https://storage.googleapis.com/seldon-models/alibi-detect/od/OutlierVAE/cifar10/model/encoder_net.h5')` 
                  
   results in:  
                  `FileNotFoundError: [Errno 2] No such file or directory: '/home/ascillitoe/.keras/datasets/my_path/OutlierVAE/model/encoder_net.h5'`

    but `tf.keras.utils.get_file(fname='encoder_net.h5',...)` works OK.
    
3. Since https://github.com/SeldonIO/alibi-detect/commit/65ed410d102c4c8f61de07c0c7c759fc609987b9 we are working with `meta.dill` and `<model>.dill`, but we are still fetching `.pickle` files from the google bucket with `fetch_detector`. This will throw up an error when `load_detector` is called in `fetch_detector`.

@matteoguarrera I presume you're actually only encountering the third issue? Hence why rolling back to a commit before https://github.com/SeldonIO/alibi-detect/commit/65ed410d102c4c8f61de07c0c7c759fc609987b9 works for you.

**Comment by ascillitoe** [comment]
Re fixes:
1. Replacing `os` operations with `pathlib` ones should be an easy fix here. 
2. I'm curious if others are experiencing this or it's just me. 
3. `utils/fetching.py` needs updating to fetch `.dill` files instead of `.pickle` (and `.dill files need to be added to google bucket). @jklaise, @arnaudvl - If we want to maintain backwards compatibility with the fetch methods in older versions we probably need to include both `.dill` and `.pickle` files in the bucket?

**Comment by ascillitoe** [comment]
Hi @matteoguarrera, the above issue should be fixed by #324. Some of the other fetch methods used in notebooks, such as `fetch_vaegmm` used in `examples/od_aegmm_kddcup.ipynb`, will still not work. This is due a small number of the models needing their state files updated on the google bucket. We will be updating this (and the example notebooks in general) soon. 

I'll close this for now, but we can of course reopen if you have any more problems. Thanks again for raising this issue.
