### ISSUE TITLE
Notebook testing automation

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi-detect#330]
Same as https://github.com/SeldonIO/alibi/issues/476.

**Comment by jklaise** [comment]
Running `nbmake` on the examples directory resulted in the following:
![image](https://user-images.githubusercontent.com/13080878/133117761-70521055-3b4d-44ba-8c2e-c08fdbf84eaf.png)

19/27 failed:

- 4 `ImportError` resulting from the `predict_batch` being made backend-specific
- `alibi_detect_deploy.ipynb` - failed as requires connection to a k8s cluster (this one we can't test within the constraints of the library - see if this can fit better in a different repo?)
- 6 `ModuleNotFoundError`
  - 3 due to dependencies specific to examples (remember to include these in a new notebook test
  - 1 potential deprecation in `sklearn` or a typo
  - 2 potential bugs due to the backend-specific models
 - 1 `RuntimeError` - couldn't find dataset (`cd_spot_the_diff_mnist_wine.ipynb`)
 - 3 Errors due to custom `ipython` kernel name (`cd_text_amazon.ipynb`, `od_seq2seq_synth.ipynb`, `cd_mol.ipynb`)
 - 2 `NameError` - `os` module not imported
 - 1 `FileNotFoundError` (`od_vae_adult.ipynb`)
 - 1 cell timeout (`cd_mmd_cifar10.ipynb`)

**Comment by ascillitoe** [comment]
The above is successfully picking up the `ImportError`'s mentioned in https://github.com/SeldonIO/alibi-detect/issues/323. 

Additionally, some notebooks cannot be completed due to `fetch` methods failing (outdated `meta.pickle` files). I think this is actually only a small number of the outlier examples (might not be exhaustive):

- od_aegmm_kddcup.ipynb
- od_prophet_weather.ipynb
- od_if_kddcup.ipynb - related to https://github.com/slundberg/shap/pull/1715.

**Note**: In some of the above notebooks `load_outlier_detector = False` is the default, so notebooks actually run unless this is changed to `True`. This is an example of where we might want to use `papermill` or similar to cover both.

**Comment by ascillitoe** [comment]
P.s. there are also some notebooks with python version dependent issues (see https://github.com/SeldonIO/alibi-detect/issues/321). Notebooks using `fetch_tf_model()` fail when loading `resnet56` on python 3.8.11 (e.g. ad_ae_cifar10.ipynb).

**Comment by jklaise** [comment]
Closed via #345. Any notebooks that still need changes should be tracked in #323.
