### ISSUE TITLE
Add conda-forge package

### ISSUE THREAD

**Issue by candalfigomoro** [SeldonIO/alibi-detect#380]
In addition to the pypi package, please add a conda-forge package (https://conda-forge.org).

You can easily create a boilerplate conda recipe with grayskull (starting from the pypi package): https://github.com/conda-incubator/grayskull

**Comment by jklaise** [comment]
@candalfigomoro thanks for raising this, we did attempt to make a conda recipe previously, but this was very tricky to do due to some odd `tensorflow` behaviour, we didn't manage to get feedback from the `conda-forge` devs on how to fix this: https://github.com/conda-forge/staged-recipes/pull/12953 . Happy to revisit this and thanks for the tool heads-up, maybe it can resolve all these issues!

**Comment by ascillitoe** [comment]
Related: #436
