### ISSUE TITLE
Unclear example

### ISSUE THREAD

**Issue by candalfigomoro** [SeldonIO/alibi-detect#391]
In this example [Categorical and mixed type data drift detection on income prediction](https://docs.seldon.io/projects/alibi-detect/en/latest/examples/cd_chi2ks_adult.html), you collect the "category map" for the adult dataset from the alibi package:

`category_map = adult.category_map`

category_map content:
```
{1: ['?',
  'Federal-gov',
  'Local-gov',
  'Never-worked',
  'Private',
  'Self-emp-inc',
  'Self-emp-not-inc',
  'State-gov',
  'Without-pay'],
 2: ['Associates',
  'Bachelors',
  'Doctorate',
  'Dropout',
  'High School grad',
  'Masters',
  'Prof-School'],
 3: ['Married', 'Never-Married', 'Separated', 'Widowed'],
 4: ['?',
  'Admin',
  'Blue-Collar',
  'Military',
  'Other',
  'Professional',
  'Sales',
  'Service',
  'White-Collar'],
 5: ['Husband',
  'Not-in-family',
  'Other-relative',
  'Own-child',
  'Unmarried',
  'Wife'],
 6: ['Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other', 'White'],
 7: ['Female', 'Male'],
 11: ['?',
  'British-Commonwealth',
  'China',
  'Euro_1',
  'Euro_2',
  'Latin-America',
  'Other',
  'SE-Asia',
  'South-America',
  'United-States',
  'Yugoslavia']}
```

Categories can be used for the `categories_per_feature` parameter of `TabularDrift`.

However, in the fetched dataset (from the alibi package), categories are label-encoded, see: https://github.com/SeldonIO/alibi/blob/master/alibi/datasets.py#L237 There are no strings, just integers.

So, what's the purpose of storing the category names (strings), when categories are label-encoded as integers? There are no more category names (strings) in the dataset, so the `category_map` no longer matches with anything in the dataset.

**Comment by RobertSamoilescu** [comment]
@candalfigomoro, I believe that your question is more related to the way we are storing the `Adult` dataset.

Note that the `Adult` dataset contains 4 important fields: `adult.data` (which we will refer as `X` - the input features), `adult.target` (which we will refer as `Y` - the labels), `adult.feature_names` (which contains the names of the features/columns) and `adult.category_map` (which contains a mapping between the categorical feature values and their corresponding label encoding, as we will discuss). 

Please note that there is a bit more structure to the dataset. We said that the `feature_names` is a list that contains the name of the feature/columns of the dataset. For the adult dataset we have: `feature_names = ['Age', 'Workclass', 'Education', ..., 'Country']`.  This is equivalent of saying that we have the following corespondance:
 * column `X[:, 0]`  corresponds to the `'Age'` feature.
 * column `X[:, 1]` corresponds to the `Workclass` feature.
 * column `X[:, 2]` corresponds to the `Education` feature.
 * ...
 * column `X[:, 11]` corresponds to the `Country` feature.

Similarly there is some structure in the `category_map` filed. For example, the following key-value pair from the `category_map`:
`1: ['?',
  'Federal-gov',
  'Local-gov',
  'Never-worked',
  'Private',
  'Self-emp-inc',
  'Self-emp-not-inc',
  'State-gov',
  'Without-pay'],`
tells us the following:
* the key `1` refers to the first categorical feature in the `feature_names`, that is `Workclass`.
* the value `['?', 'Federal-gov', ...]` tells us the label encoding by looking at each feature value index. That is: `'?'` is label encoded as `0`, `'Federal-gov'` is label encoded as `1`, `'Local-gov'` is label encoded as `2`, and so on ...

Thus, both the `feature_names` and `category_map` can be seen as bijective mappings between the index<->feature names and label encoding <-> feature values. Note that the `category_map` contains information only about the categorical features (i.e., the keys are the column indices of the categorical features and the values are their corresponding feature values).

Having said that, we can transform our `X` dataset into a more readable format. For example, if we have the following instance:
`[39, 7, 1, 1, 1, 1, 4, 1, 2174, 0, 40, 9]` we transform it to:

|Age | Workclass | Education | ... | Country          |
|------|---------------|---------------|-----|--------------------|
| 39  | State-gov | Bachelors  | ...  | United-States |

Now, from the detector point of view, the only way we used the `category_map` is to extract the indices of the columns corresponding to the categorical features, which are stored as keys. We store this information in the dictionary `categories_per_feature` which has as key the column index and as values, `None`.

```python
categories_per_feature = {f: None for f in list(category_map.keys())}
```
We need to differentiate between numerical and categorical features because we apply different tests statistics (i.e., KS for numerical features and Chi-square for categorical features.)

We set the values to `None` because the detector is smart enough to infer all the feature values for each categorical column, by looking at the unique values that appear in each categorical column of the ref/test datasets that we send as arguments. This step of inferring the feature values it is possible because the `X`'s that we pass are already labeled encoded (i.e. are `int` variable as expected by the backend which can be seen as a design choice) and has to do with the following lines:

https://github.com/SeldonIO/alibi-detect/blob/3a3e84bb3e15287d31b11862d160efa6a9dd2f9a/alibi_detect/cd/tabular.py#L84-L87

Finally, the `category_map` is used again for plotting, where we transform back the label encoded feature values to their string representation.

Hope this helps answering your question. Please let me know if you need more clarification or if I missed something from your question. Thanks!

**Comment by candalfigomoro** [comment]
Thanks!
