### ISSUE TITLE
Creating Docker Image

### ISSUE THREAD

**Issue by Abhinav-Anil** [SeldonIO/alibi-detect#415]
Hi,

How can I create docker image for alibi-detect?
Approaches I tried:
1.  RUN pip3 install alibi-detect
2. Another way I cloned the repo and then tried to run setup.py

It fails with both approaches.
Please help and guide in this issue.

@ahousley @tchellam

**Comment by ascillitoe** [comment]
Hi @Abhinav-Anil, thanks for raising this issue. I've just had a quick go at building a docker image and also ran into trouble on the first attempt. When using the `python:3.8` docker image I get `ImportError: libGL.so.1: cannot open shared object file: No such file or directory` when attempting to run `import alibi_detect`. 

Is this the same error you experienced? If so, this is due to the OpenCV dependencies not being present on the `python:3.8` docker image (they are present on most non-docker systems so not usually an issue). A simple approach to fix this is to run `apt-get install -y python3-opencv`. Below I've included an example workflow that should provide a working image for alibi-detect, but you might need to edit it for your purposes. Please also let us know if you're experiencing a different failure and we can look into it further. 

#### Solution

1. Clone the latest alibi-detect version:
```
git clone https://github.com/SeldonIO/alibi-detect.git --branch v0.8.0 --single-branch
```

2. Create a simple `Dockerfile`:
```
# set base image (host OS)
FROM python:3.8

# Install OpenCV dependencies
RUN apt-get update && apt-get install -y python3-opencv

# set the working directory in the container
WORKDIR /app

# copy alibi-detect to the working directory
COPY alibi-detect .

# install alibi-detect
RUN pip install .
```

3. Build the docker image:
```
docker build -t detect_image .
```

4. Run the docker image interactively:
```
sudo docker run -it detect_image
```

5. In the resulting python terminal, briefly test `alibi_detect`:
```
import numpy as np
from alibi_detect.cd import MMDDrift
x_ref = np.random.normal(size=(100,2))
cd = MMDDrift(x_ref)
cd.predict(x_ref)
```

**Comment by Abhinav-Anil** [comment]
ERROR: Could not find a version that satisfies the requirement tensorflow<2.6.0,>=2.0.0 (from alibi-detect) (from versions: none)                                                                                  
ERROR: No matching distribution found for tensorflow<2.6.0,>=2.0.0

It is showing the tensorflow error while follow the approach that you had suggested.

I have tried to install alibi-detect in /bin/bash also. It got failed.

**Comment by ascillitoe** [comment]
Is this the same error you were getting before or a new one? Also, did pip successfully install anything else before getting to tensorflow?

**Comment by ascillitoe** [comment]
Hi @Abhinav-Anil, are you still having issues with this? Or can we close?

**Comment by Abhinav-Anil** [comment]
I was trying solve it with python 3.6.9, issue is still occurred.  We can close it now.
But, if again major issue occur I'll reopen it.

Thanks

**Comment by ascillitoe** [comment]
Thanks @Abhinav-Anil!
