### ISSUE TITLE
Tensorflow GPU Memory Cost

### ISSUE THREAD

**Issue by GeorgeWu97** [SeldonIO/alibi-detect#449]
Upon import alibi_detect, Tensorflow backend would automatically occupy all the GPU memory.
Is there any method to control the memory growth as Tensorflow api?

**Comment by ascillitoe** [comment]
Hi @GeorgeWu97, we don't do anything particularly bespoke with the Tensorflow configuration, so you should hopefully be able to manage your GPU memory usage via the strategies outlined in [this TensorFlow doc](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth). More specifically, by either turning on "memory growth" for Tensorflow with ` tf.config.experimental.set_memory_growth(gpu, True)` or the `TF_FORCE_GPU_ALLOW_GROWTH` env variable. Or, by setting a `memory_limit`. You will likely have to do either of these prior to running `import alibi_detect`. 

Please let us know if this helps, otherwise, we will look into what else can be done.

**Comment by GeorgeWu97** [comment]
>

**Comment by GeorgeWu97** [comment]
> Hi @GeorgeWu97, we don't do anything particularly bespoke in terms of configuring the Tensorflow enviroment/session, so you should hopefully be able to manage your GPU memory usage via the strategies outlined in [this TensorFlow doc](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth). More specifically, by either turning on "memory growth" for Tensorflow with ` tf.config.experimental.set_memory_growth(gpu, True)` or the `TF_FORCE_GPU_ALLOW_GROWTH` env variable. Or, by setting a `memory_limit`. You will likely have to do either of these prior to running `import alibi_detect`.
> 
> Please let us know if this helps, otherwise, we will look into what else can be done.

Setting memory growth before import alibi_detect works, thanks.

**Comment by ascillitoe** [comment]
Great, thanks!
