### ISSUE TITLE
Wrong result in MMD with my own dataset

### ISSUE THREAD

**Issue by AlexJRC** [SeldonIO/alibi-detect#544]
Hello

I tried to replicate the study done by MMD in [cifar10](https://docs.seldon.io/projects/alibi-detect/en/stable/examples/cd_mmd_cifar10.html), in a dataset of my own (only changed X_train, y_train ,X_test,  y_test), keeping the original structure of the code, only modifying the input data. However, I ran into some problems:

1 - When I put two equal sets (in theory it wasn't supposed to show drift), my model is returning to me:

> ![drift](https://user-images.githubusercontent.com/73409467/176571813-2eb0558e-dd5a-4c0b-bda5-047b050e9370.png)

I think the problem may be in parts of the old framework code
![erro_drift](https://user-images.githubusercontent.com/73409467/176572292-36e59092-457e-4a33-a475-7685f86510a8.png)

like the **function fetch_cifar10c in X_corr, y_corr**, because I'm not using the cifar10 dataset anymore.
or maybe **corruption**, because how I am used my own data, I not need create different data.

Or yet the problem can be in this function:
![funcion](https://user-images.githubusercontent.com/73409467/176573426-5bb68e76-62be-4759-827c-6f6b9ee45c87.png)

I Tried to find the solution, but I did not achieve it. Does anyone have any idea that can be this problem, and how I resolve it?

**Comment by Srceh** [comment]
Hi @AlexJRC , 

It is hard to tell from the current screenshots as they don't give the overall pipeline.

It seems you still use the `x_corr` variable which is loaded from cifar10c, but you mentioned that you replaced the `x_trian, x_test` with your own data?

**Comment by AlexJRC** [comment]
Yes @Srceh  i yet use the x_corr in my code:

[Google Colab](https://colab.research.google.com/drive/1Qjf5vXC8C1utAhod5J3C1_CQa6HCPxZ0?usp=sharing
)
my dataset:
[Google Drive](https://drive.google.com/drive/folders/1o5eEL2ZvBn9yPHa1ujUFSeU111AZYKCg?usp=sharing
)

Thank you for your help!

**Comment by ascillitoe** [comment]
Hi @AlexJRC, the `make_predictions` and `fetch_cifar10` functions are utility functions used in the CIFAR10 MMD example in order to allow us to demonstrate use of `MMDDrift` with different types of image corruption. It looks to me like these functions are confusing a fair bit of confusion in your notebook. I would advise deleting these functions entirely and going back to basics. I believe a relatively simple workflow like that described [in the docs](https://docs.seldon.io/projects/alibi-detect/en/stable/cd/methods/mmddrift.html) should work for you. For example:

```python
from functools import partial
import torch
import torch.nn as nn
from alibi_detect.cd.pytorch import preprocess_drift

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# define encoder
encoder_net = nn.Sequential(
    nn.Conv2d(3, 64, 4, stride=2, padding=0),
    nn.ReLU(),
    nn.Conv2d(64, 128, 4, stride=2, padding=0),
    nn.ReLU(),
    nn.Conv2d(128, 512, 4, stride=2, padding=0),
    nn.ReLU(),
    nn.Flatten(),
    nn.Linear(2048, 32)
).to(device).eval()

# define preprocessing function
preprocess_fn = partial(preprocess_drift, model=encoder_net, device=device, batch_size=512)

detector = MMDDrift(x_ref, backend='pytorch', p_val=.05, preprocess_fn=preprocess_fn)
```

(you might need to tweak your `encoder_net` according to the dimensions of your image data. Once your `detector` is defined, you can pass it test data via `detector.predict()`. 

All the complexity in the cifar10 notebook with `make_predictions` and `fetch_cifar10` is in order to obtain suitable drifted and non-drifted data to pass to `predict`. If you already have test data you can simply pass this to `predict` yourself. If you only have non-drifted data, you can add drift by perturbing your images (i.e. blurring etc) using the utility functions in [alibi_detect.utils.perturbation](https://docs.seldon.io/projects/alibi-detect/en/stable/api/alibi_detect.utils.perturbation.html). Please do let us know how you get on 🙂
