### ISSUE TITLE
Different results in fisher's exact test compared with scipy for single feature

### ISSUE THREAD

**Issue by SangamSwadiK** [SeldonIO/alibi-detect#660]
Hi, 
I was exploring the` fisher's exact test` from the drift detection module, 
After exploring for a while, I compared the results of the fisher exact test in `alibi-detect` with `scipy.stats.fisher_exact` for 
single feature for the below data (have used alternative as two-sided for both cases)

`x_ref = pd.Series([0,0, 1, 1]).values`
`x_cur = pd.Series([0,0, 1, 1]).values
`
The `FET Detector` is giving me a `p-value of 1` where-as  `scipy,stats.fisher_exact` is giving me a `p value of 0.333`, I found other similar cases. I did go through the code,  over **[fet.py](https://github.com/SeldonIO/alibi-detect/blob/6df9bd4b0fb6b27a1df41f0cdae76c804dc3cd55/alibi_detect/cd/fet.py#L109)**

I'm trying to understand why it is different.
Can you please explain what exactly [line-117](https://github.com/SeldonIO/alibi-detect/blob/6df9bd4b0fb6b27a1df41f0cdae76c804dc3cd55/alibi_detect/cd/fet.py#L117)  is doing ? 

Thanks !

**Comment by jklaise** [comment]
Hi @SangamSwadiK. Can you confirm how you are using the `scipy.stats.fisher_exact` function (i.e. what is the input to it)?

Note that `scipy.stats.fisher_exact` takes as argument a 2x2 contingency table of counts of `0`'s and `1`'s for each dataset, whereas our detector `FETDrift` operates on the raw binary data (`x_ref` and `x_cur`) directly. Line 117 in our code is just constructing the contingency table internally before calling `scipy.stats.fisher_exact` on it.

To clarify, you get the same result (a p-value of 1) using both methods. Note that using `fisher_exact` you need to construct the contingency table manually - in your example it is just a 2x2 table where every entry is `2` because there are 2 occurences of `0` and `1` in both sets of data:

```python
from alibi_detect.cd import FETDrift
from scipy.stats import fisher_exact

x_ref = np.array([0, 0, 1, 1])
x_cur = np.array([0, 0, 1, 1])

# Alibi
fet = FETDrift(x_ref, alternative='two-sided')
pred = fet.predict(x_cur)
print(pred['data']['p_val'])  #  [1.]

# Scipy
table = np.array([[2, 2], [2, 2]])  # for each of x_ref and x_cur there are 2 occurences of 0 and 1 each
_, p_val = fisher_exact(table)
print(p_val) # 1.0
```

I hope that helps, there's more detail about the method in our [docs](https://docs.seldon.io/projects/alibi-detect/en/latest/cd/methods/fetdrift.html#Overview).
