### ISSUE TITLE
Access scores as attribute preds.data.instance_score 

### ISSUE THREAD

**Issue by mishinma** [SeldonIO/alibi-detect#75]
It would be nice to be able to access prediction scores as  `preds.data.instance_score` instead of `preds["data"]["instance_score"]`. Could be accomplished with `addict` https://github.com/mewwts/addict (also `Bunch` could be replaced with `addict` if it doesn't serve other purpose). This is just a personal opinion though, feel free to ignore. :)

**Comment by jklaise** [comment]
I think in the future we will move to custom objects rather than using Python dictionaries (which is the plan for Alibi), in which case one would have 2-level attribute access (e.g. both `preds.data` returning a dict and `preds.instance_score` returning the scores). I've thought about a more general solution using e.g. `Bunch` as you suggest, but the main downside would be that numerical indices can't be accessed as attributes which might make the whole thing more confusing.

**Comment by mishinma** [comment]
@jklaise makes sense. I think it's done that way in FAIR's Detectron too. I will close this
