### ISSUE TITLE
The kddcup isolation forest artefact needs updating with `sklearn 1.3.0`

### ISSUE THREAD

**Issue by ascillitoe** [SeldonIO/alibi-detect#827]
The `fetch_detector` call run by `od_if_kddcup.ipynb` returns the following warning (which leads to an error):

```
 InconsistentVersionWarning: Trying to unpickle estimator ExtraTreeRegressor from version 1.0 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk.
```

It is likely we need to regenerate `https://console.cloud.google.com/storage/browser/seldon-models/alibi-detect/od/IForest/kddcup` with `sklearn 1.3.0`.

**Comment by jklaise** [comment]
See this for confirmation: https://github.com/scikit-learn/scikit-learn/issues/26798

In general I would lean towards removing persisting `scikit-learn` based models specifically because they don't support cross-version persistence. Since we're a library, supporting this so it never fails would essentially require us to produce an artifact and upload it (ideally automatically) for every `scikit-learn` version that the user may run which is too much to ask.

I'll check what the fitting times are on the examles using `scikit-learn` models and report back, I don't believe it would any larger than some of our GPU-based notebooks (albeit we don't run those through CI).

**Comment by jklaise** [comment]
As a minimum we should wrap the loading in notebooks in `try/except` so the user isn't immediately errored out.

**Comment by jklaise** [comment]
This comment is to track pre-trained `sklearn` model/detector usage in our docs:
 - `od_if_kddcup.ipynb` - load by default, training only takes ~1/2 sec
 - `od_mahalanobis_kddcup` - don't load by default (so no error - interestingly, loading the old artifact works fine), training takes, training only takes 5-10ms
